services:
  database:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=habits
    ports:
      - "5432:5432"
    volumes:
      - ./db/:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d admin"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - nw

  app:
    build:
      context: .
    command: python app/main.py
    depends_on:
      database:
        condition: service_healthy
        restart: true
    networks:
      - nw

  bot:
    build:
      context: .
    command: python main.py
    networks:
      - nw


networks:
  nw:
    driver: bridge
